DROP DATABASE DB_ACADEMIA;
CREATE DATABASE DB_ACADEMIA;

USE DB_ACADEMIA;

CREATE TABLE TB_ATIVIDADES(
ID_ATIVIDADE INT NOT NULL AUTO_INCREMENT,
NOME_ATIVIDADE VARCHAR(45) NOT NULL,

PRIMARY KEY(ID_ATIVIDADE)
);

CREATE TABLE TB_INSTRUTORES(
RG_INSTRUTOR VARCHAR(12) NOT NULL,
NOME_INSTRUTOR VARCHAR(45) NOT NULL,
NASCIMENTO_INSTRUTOR DATE,
TITULACAO_INSTRUTOR VARCHAR(45) NOT NULL,
TELEFONE_INSTRUTOR VARCHAR(10),

PRIMARY KEY(RG_INSTRUTOR)
);

CREATE TABLE TB_ALUNOS(
ID_ALUNO INT NOT NULL,
DATA_MATRICULA DATE NOT NULL,
NOME_ALUNO VARCHAR(45) NOT NULL,
ENDERECO_ALUNO VARCHAR(45),
TELEFONE_ALUNO VARCHAR(10),
NASCIMENTO_ALUNO DATE NOT NULL,
ALTURA_ALUNO DECIMAL(2, 1),
PESO_ALUNO DECIMAL(3, 2),

PRIMARY KEY(ID_ALUNO)
);

CREATE TABLE TB_MONITORES(
ID_MONITOR INT NOT NULL AUTO_INCREMENT,
ID_ALUNO INT NOT NULL,

PRIMARY KEY(ID_MONITOR),
FOREIGN KEY(ID_ALUNO) REFERENCES TB_ALUNOS(ID_ALUNO)
);

CREATE TABLE TB_TURMAS(
ID_TURMA INT NOT NULL AUTO_INCREMENT,
QTD_ALUNOS INT NOT NULL,
HORARIO_AULA DATETIME NOT NULL,
DURACAO_AULA DATETIME NOT NULL,
DATA_INICIO DATE NOT NULL,
DATA_FIM DATE,
ID_ATIVIDADE INT NOT NULL,
RG_INSTRUTOR VARCHAR(12) NOT NULL,
ID_MONITOR INT NOT NULL,
ID_ALUNO INT NOT NULL,

PRIMARY KEY(ID_TURMA),
FOREIGN KEY(ID_ATIVIDADE) REFERENCES TB_ATIVIDADES(ID_ATIVIDADE),
FOREIGN KEY(RG_INSTRUTOR) REFERENCES TB_INSTRUTORES(RG_INSTRUTOR),
FOREIGN KEY(ID_MONITOR) REFERENCES TB_MONITORES(ID_MONITOR),
FOREIGN KEY(ID_ALUNO) REFERENCES TB_ALUNOS(ID_ALUNO)
);

CREATE TABLE TB_REGISTROS(
ID_REGISTRO INT NOT NULL AUTO_INCREMENT,
FALTAS INT,
ID_ALUNO INT NOT NULL,
ID_TURMA INT NOT NULL,

PRIMARY KEY(ID_REGISTRO),
FOREIGN KEY(ID_ALUNO) REFERENCES TB_ALUNOS(ID_ALUNO),
FOREIGN KEY(ID_TURMA) REFERENCES TB_TURMAS(ID_TURMA)
);