DROP DATABASE DB_CLINICA_MEDICA;
CREATE DATABASE DB_CLINICA_MEDICA;

USE DB_CLINICA_MEDICA;

CREATE TABLE TB_MEDICOS(
ID_MED INT NOT NULL AUTO_INCREMENT,
NOME_MED VARCHAR(45) NOT NULL,
TELEFONE_MED VARCHAR(10) NOT NULL,

PRIMARY KEY(ID_MED)
);

CREATE TABLE TB_PACIENTES(
ID_PAC INT NOT NULL AUTO_INCREMENT,
NOME_PAC VARCHAR(45) NOT NULL,
TELEFONE_PAC VARCHAR(10) NOT NULL,
CONVENIO VARCHAR(45),

PRIMARY KEY(ID_PAC)
);

CREATE TABLE TB_RECEITAS_MEDICAS(
ID_REC INT NOT NULL AUTO_INCREMENT,
DESCRICAO VARCHAR(500) NOT NULL,

PRIMARY KEY(ID_REC)
);

CREATE TABLE TB_CONSULTAS(
ID_CON INT NOT NULL AUTO_INCREMENT,
DATA_CON DATETIME NOT NULL,
ID_MED INT NOT NULL,
ID_PAC INT NOT NULL,
ID_REC INT NOT NULL,

PRIMARY KEY(ID_CON),
FOREIGN KEY(ID_MED) REFERENCES TB_MEDICOS(ID_MED),
FOREIGN KEY(ID_PAC) REFERENCES TB_PACIENTES(ID_PAC),
FOREIGN KEY(ID_REC) REFERENCES TB_RECEITAS_MEDICAS(ID_REC)
);