DROP DATABASE DB_EQUIPE_VENDAS;
CREATE DATABASE DB_EQUIPE_VENDAS;

USE DB_EQUIPE_VENDAS;

CREATE TABLE TB_PRODUTOS(
ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
NOME_PRODUTO VARCHAR(45) NOT NULL,

PRIMARY KEY(ID_PRODUTO)
);

CREATE TABLE TB_EQUIPES(
ID_EQUIPE INT NOT NULL AUTO_INCREMENT,
NOME_EQUIPE  VARCHAR(45) NOT NULL,

PRIMARY KEY(ID_EQUIPE)
);

CREATE TABLE TB_VENDEDORES(
ID_VENDEDOR INT NOT NULL AUTO_INCREMENT,
NOME_VENDEDOR VARCHAR(45) NOT NULL,

PRIMARY KEY(ID_VENDEDOR)
);

CREATE TABLE TB_VENDAS(
ID_VENDA INT NOT NULL AUTO_INCREMENT,
ID_VENDEDOR INT NOT NULL,
ID_PRODUTO INT NOT NULL,
ID_EQUIPE INT NOT NULL,

PRIMARY KEY(ID_VENDA),
FOREIGN KEY(ID_VENDEDOR) REFERENCES TB_VENDEDORES(ID_VENDEDOR),
FOREIGN KEY(ID_PRODUTO) REFERENCES TB_PRODUTOS(ID_PRODUTO),
FOREIGN KEY(ID_EQUIPE) REFERENCES TB_EQUIPES(ID_EQUIPE)
);